fix: Make sure correct data is displayed for trips#index and trips#sh…
IgorrMagalhaess/hop_hop_be pull request #32
Opened 2024-04-14 01:13 UTC by yainporter

## Type of change
- [x] New feature
- [x] Bug Fix
- [x] Test
- [ ] Refactor/Style

## Description
Relevant User Story(s):
*Brief summary of the change(s) included in this pull request*
- Changed port to localhost:5000
- Fixed some swagger_helper.rb data to display more fully for api-docs
- Changed texts to display correct data for api-docs
- Added `gem "rack-cors"` so that api-docs can work correctly
- Enabled `cors.rb`
- Changed datatypes to align with openapi documentation

This description closes #

## Check the correct boxes
- [x] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

## Testing Changes
- [ ] No Tests have been changed
- [x] Some Tests have been changed
- [ ] All of the Tests have been changed

*Please describe what in the world happened if tests are broken*

## Checklist:
- [x] My code has no unused/commented out code
- [x] I have reviewed my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have fully tested my code

## Fun fact or favorite .gif:

2024-04-14 11:55 UTC, IgorrMagalhaess approved these changes

2024-04-15 04:29 UTC, Selena730 commented on config/puma.rb
nice catch!

2024-04-15 04:31 UTC, Selena730 approved these changes
Thank you Yain!

2024-04-15 04:56 UTC, hoadam requested changes

2024-04-15 04:56 UTC, hoadam commented on app/controllers/api/v1/trips_controller.rb
> +      if filter_user_trips.empty?
why do we need to check if empty? we can just return empty array if users dont have trip yet.

2024-04-15 05:04 UTC, closed without merging